---
- ignore:
    name: "Use camelCase"

- ignore:
    name: "Unused LANGUAGE pragma"
    within:
      - "Unicode.Grapheme"
      - "Unit.Unicode.Grapheme"

- ignore:
    name: "Redundant bracket"
    within:
      - "Unicode.Grapheme"
      - "Unicode.Grapheme.Internal.ClusterState"
